## Benchmark-specific linter rules

env:
  node: true
  es6: true

rules:
  prefer-arrow-callback: error

overrides:
  - files:
      - async_hooks/*.js
      - buffers/*.js
      - buffers-fill/*.js
      - crypto/*.js
      - http/*.js
      - http2/*.js
      - misc/*.js
      - module/*.js
      - net/*.js
      - path/*.js
      - process/*.js
      - url/*.js
      - util/*.js
    rules:
      comma-dangle: [error, {
        arrays: always-multiline,
        exports: always-multiline,
        functions: only-multiline,
        imports: always-multiline,
        objects: only-multiline,
      }]
