// Auto-generated by `node tools/doc/addon-verify.js`
'use strict';
const common = require('../../common');
// test.js
const binding = require(`./build/${common.buildType}/binding`);

const obj = new binding.MyObject(10);
console.log(obj.plusOne());
// Prints: 11
console.log(obj.plusOne());
// Prints: 12
console.log(obj.plusOne());
// Prints: 13
