#!/bin/bash

# Copyright (c) 2009 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

python ../../../gyp --debug variables --format gypd --depth . commands.gyp > commands.gyp.stdout
python ../../../gyp --ignore-environment --debug variables --format gypd --depth . commands.gyp > commands.gyp.ignore-env.stdout
cp -f commands.gypd commands.gypd.golden
python ../../../gyp --debug variables --format gypd --depth . commands-repeated.gyp > commands-repeated.gyp.stdout
cp -f commands-repeated.gypd commands-repeated.gypd.golden
