// Auto-generated by `node tools/doc/addon-verify.js`
'use strict';
const common = require('../../common');
// test.js
const binding = require(`./build/${common.buildType}/binding`);

binding((msg) => {
  console.log(msg);
// Prints: 'hello world'
});
