// Auto-generated by `node tools/doc/addon-verify.js`
'use strict';
const common = require('../../common');
// test.js
const binding = require(`./build/${common.buildType}/binding`);

const fn = binding();
console.log(fn());
// Prints: 'hello world'
