name: Run undici WPT (legacy)
description: Runs undici WPT tests for undici < 7 and appends results to the Node.js WPT report

inputs:
  undici-version:
    required: true
    description: undici version tag to checkout
  wpt-report:
    required: true
    description: Path to the Node.js WPT report

runs:
  using: composite
  steps:
    - name: Checkout undici
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        repository: nodejs/undici
        persist-credentials: false
        path: undici
        clean: false
        ref: ${{ inputs.undici-version }}
    - name: Prepare WPT checkout
      shell: bash
      run: |
        rm -rf undici/test/wpt/tests
        mv test/fixtures/wpt undici/test/wpt/tests
    - name: Install dependencies
      shell: bash
      working-directory: undici
      run: npm install
    - name: Run WPT
      shell: bash
      working-directory: undici
      env:
        WPT_REPORT: ${{ inputs.wpt-report }}
      run: npm run test:wpt || true
