extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  comments-indentation:
    level: error

  document-end:
    present: false

  document-start:
    level: error
    present: false

  empty-lines:
    max: 1

  indentation:
    spaces: 2

  line-length: disable

  quoted-strings:
    quote-type: single
    required: only-when-needed

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  /deps/
  node_modules/
  /test/fixtures/wpt/
  /tools/gyp/
  /tools/pip/
