# TODO(bcoe): re-enable coverage report comments, once we can figure out
# how to make them more accurate for the Node.js project,
# See: https://github.com/nodejs/node/issues/35759
comment: false
#  # Only show diff and files changed:
#  layout: "diff, files"
#  # Don't post if no changes in coverage:
#  require_changes: true

codecov:
  branch: main
  notify:
    # Wait for all coverage builds:
    after_n_builds: 2

coverage:
  status:
    project: off
    patch: off
