#!/bin/bash

# GitHub PR Merge & Close Script
# Merges all feature/UX PRs and closes duplicate documentation PRs
# Usage: bash merge-all-features.sh

set -e

echo "Starting feature PR merge and duplicate cleanup..."
echo "================================"

# MERGE ALL ADK-JS FEATURE/UX PRs (Palette CLI improvements)
echo "Merging ADK-JS Palette CLI UX PRs..."

gh pr merge piyyy314/adk-js/88 --merge || echo "⚠️  Failed to merge adk-js#88"
gh pr merge piyyy314/adk-js/87 --merge || echo "⚠️  Failed to merge adk-js#87"
gh pr merge piyyy314/adk-js/86 --merge || echo "⚠️  Failed to merge adk-js#86"
gh pr merge piyyy314/adk-js/85 --merge || echo "⚠️  Failed to merge adk-js#85"
gh pr merge piyyy314/adk-js/84 --merge || echo "⚠️  Failed to merge adk-js#84"
gh pr merge piyyy314/adk-js/83 --merge || echo "⚠️  Failed to merge adk-js#83"
gh pr merge piyyy314/adk-js/82 --merge || echo "⚠️  Failed to merge adk-js#82"
gh pr merge piyyy314/adk-js/81 --merge || echo "⚠️  Failed to merge adk-js#81"
gh pr merge piyyy314/adk-js/80 --merge || echo "⚠️  Failed to merge adk-js#80"
gh pr merge piyyy314/adk-js/78 --merge || echo "⚠️  Failed to merge adk-js#78"
gh pr merge piyyy314/adk-js/74 --merge || echo "⚠️  Failed to merge adk-js#74"
gh pr merge piyyy314/adk-js/73 --merge || echo "⚠️  Failed to merge adk-js#73"
gh pr merge piyyy314/adk-js/72 --merge || echo "⚠️  Failed to merge adk-js#72"
gh pr merge piyyy314/adk-js/71 --merge || echo "⚠️  Failed to merge adk-js#71"
gh pr merge piyyy314/adk-js/68 --merge || echo "⚠️  Failed to merge adk-js#68"
gh pr merge piyyy314/adk-js/66 --merge || echo "⚠️  Failed to merge adk-js#66"
gh pr merge piyyy314/adk-js/65 --merge || echo "⚠️  Failed to merge adk-js#65"
gh pr merge piyyy314/adk-js/64 --merge || echo "⚠️  Failed to merge adk-js#64"
gh pr merge piyyy314/adk-js/63 --merge || echo "⚠️  Failed to merge adk-js#63"
gh pr merge piyyy314/adk-js/62 --merge || echo "⚠️  Failed to merge adk-js#62"
gh pr merge piyyy314/adk-js/61 --merge || echo "⚠️  Failed to merge adk-js#61"
gh pr merge piyyy314/adk-js/60 --merge || echo "⚠️  Failed to merge adk-js#60"
gh pr merge piyyy314/adk-js/59 --merge || echo "⚠️  Failed to merge adk-js#59"
gh pr merge piyyy314/adk-js/58 --merge || echo "⚠️  Failed to merge adk-js#58"
gh pr merge piyyy314/adk-js/57 --merge || echo "⚠️  Failed to merge adk-js#57"
gh pr merge piyyy314/adk-js/56 --merge || echo "⚠️  Failed to merge adk-js#56"
gh pr merge piyyy314/adk-js/55 --merge || echo "⚠️  Failed to merge adk-js#55"
gh pr merge piyyy314/adk-js/54 --merge || echo "⚠️  Failed to merge adk-js#54"
gh pr merge piyyy314/adk-js/52 --merge || echo "⚠️  Failed to merge adk-js#52"
gh pr merge piyyy314/adk-js/50 --merge || echo "⚠️  Failed to merge adk-js#50"
gh pr merge piyyy314/adk-js/49 --merge || echo "⚠️  Failed to merge adk-js#49"
gh pr merge piyyy314/adk-js/48 --merge || echo "⚠️  Failed to merge adk-js#48"
gh pr merge piyyy314/adk-js/47 --merge || echo "⚠️  Failed to merge adk-js#47"
gh pr merge piyyy314/adk-js/46 --merge || echo "⚠️  Failed to merge adk-js#46"
gh pr merge piyyy314/adk-js/42 --merge || echo "⚠️  Failed to merge adk-js#42"
gh pr merge piyyy314/adk-js/41 --merge || echo "⚠️  Failed to merge adk-js#41"
gh pr merge piyyy314/adk-js/40 --merge || echo "⚠️  Failed to merge adk-js#40"
gh pr merge piyyy314/adk-js/39 --merge || echo "⚠️  Failed to merge adk-js#39"
gh pr merge piyyy314/adk-js/37 --merge || echo "⚠️  Failed to merge adk-js#37"
gh pr merge piyyy314/adk-js/35 --merge || echo "⚠️  Failed to merge adk-js#35"
gh pr merge piyyy314/adk-js/30 --merge || echo "⚠️  Failed to merge adk-js#30"
gh pr merge piyyy314/adk-js/29 --merge || echo "⚠️  Failed to merge adk-js#29"
gh pr merge piyyy314/adk-js/28 --merge || echo "⚠️  Failed to merge adk-js#28"
gh pr merge piyyy314/adk-js/27 --merge || echo "⚠️  Failed to merge adk-js#27"
gh pr merge piyyy314/adk-js/26 --merge || echo "⚠️  Failed to merge adk-js#26"
gh pr merge piyyy314/adk-js/25 --merge || echo "⚠️  Failed to merge adk-js#25"
gh pr merge piyyy314/adk-js/20 --merge || echo "⚠️  Failed to merge adk-js#20"
gh pr merge piyyy314/adk-js/14 --merge || echo "⚠️  Failed to merge adk-js#14"
gh pr merge piyyy314/adk-js/13 --merge || echo "⚠️  Failed to merge adk-js#13"
gh pr merge piyyy314/adk-js/12 --merge || echo "⚠️  Failed to merge adk-js#12"
gh pr merge piyyy314/adk-js/11 --merge || echo "⚠️  Failed to merge adk-js#11"
gh pr merge piyyy314/adk-js/10 --merge || echo "⚠️  Failed to merge adk-js#10"
gh pr merge piyyy314/adk-js/6 --merge || echo "⚠️  Failed to merge adk-js#6"
gh pr merge piyyy314/adk-js/5 --merge || echo "⚠️  Failed to merge adk-js#5"
gh pr merge piyyy314/adk-js/4 --merge || echo "⚠️  Failed to merge adk-js#4"
gh pr merge piyyy314/adk-js/3 --merge || echo "⚠️  Failed to merge adk-js#3"
gh pr merge piyyy314/adk-js/2 --merge || echo "⚠️  Failed to merge adk-js#2"

echo ""
echo "================================"
echo "Merging Shiatoali- Documentation - LATEST ONLY (keeping most recent)"
echo "Merging PR #37 (latest - 13 hours old)..."
gh pr merge piyyy314/Shiatoali-/37 --merge || echo "⚠️  Failed to merge Shiatoali-#37"

echo ""
echo "================================"
echo "Closing Shiatoali- duplicate documentation PRs..."

# Close all duplicate Blockscout documentation PRs (keeping #37 as the latest)
gh pr close piyyy314/Shiatoali-/36 || echo "⚠️  Failed to close Shiatoali-#36"
gh pr close piyyy314/Shiatoali-/35 || echo "⚠️  Failed to close Shiatoali-#35"
gh pr close piyyy314/Shiatoali-/34 || echo "⚠️  Failed to close Shiatoali-#34"
gh pr close piyyy314/Shiatoali-/33 || echo "⚠️  Failed to close Shiatoali-#33"
gh pr close piyyy314/Shiatoali-/32 || echo "⚠️  Failed to close Shiatoali-#32"
gh pr close piyyy314/Shiatoali-/31 || echo "⚠️  Failed to close Shiatoali-#31"
gh pr close piyyy314/Shiatoali-/30 || echo "⚠️  Failed to close Shiatoali-#30"
gh pr close piyyy314/Shiatoali-/28 || echo "⚠️  Failed to close Shiatoali-#28"
gh pr close piyyy314/Shiatoali-/27 || echo "⚠️  Failed to close Shiatoali-#27"
gh pr close piyyy314/Shiatoali-/26 || echo "⚠️  Failed to close Shiatoali-#26"
gh pr close piyyy314/Shiatoali-/24 || echo "⚠️  Failed to close Shiatoali-#24"
gh pr close piyyy314/Shiatoali-/15 || echo "⚠️  Failed to close Shiatoali-#15"
gh pr close piyyy314/Shiatoali-/6 || echo "⚠️  Failed to close Shiatoali-#6"
gh pr close piyyy314/Shiatoali-/5 || echo "⚠️  Failed to close Shiatoali-#5"
gh pr close piyyy314/Shiatoali-/4 || echo "⚠️  Failed to close Shiatoali-#4"
gh pr close piyyy314/Shiatoali-/1 || echo "⚠️  Failed to close Shiatoali-#1"

echo ""
echo "================================"
echo "Merging other feature PRs..."

# Merge other feature/template PRs from various repos
gh pr merge piyyy314/snyk/cli/6936 --merge || echo "⚠️  Failed to merge snyk/cli#6936"
gh pr merge piyyy314/g1nt0ki/yield-server/2 --merge || echo "⚠️  Failed to merge yield-server#2"
gh pr merge piyyy314/g1nt0ki/yield-server/1 --merge || echo "⚠️  Failed to merge yield-server#1"
gh pr merge piyyy314/jkid88/AI-1/1 --merge || echo "⚠️  Failed to merge AI-1#1"
gh pr merge piyyy314/pitty313-yield-server/23 --merge || echo "⚠️  Failed to merge pitty313-yield-server#23"

echo ""
echo "================================"
echo "✅ Feature PRs merged and duplicates closed!"
echo ""
echo "Summary:"
echo "  ✓ Merged ~58 adk-js CLI UX improvement PRs (Palette)"
echo "  ✓ Merged latest Shiatoali- documentation PR (#37)"
echo "  ✓ Closed 16 duplicate Shiatoali- documentation PRs"
echo "  ✓ Merged other feature/template PRs"
echo ""
echo "Total: ~79 feature/UX PRs processed"
