// Auto-generated by scripts/bundle.mjs — do not edit; edit src/keys.mjs in NoNoSQLite.
'use strict';

const {
  ArrayIsArray,
  ArrayPrototypeJoin,
  ArrayPrototypeMap,
  ArrayPrototypeSlice,
  ArrayPrototypeSome,
  BigIntPrototypeToString,
  NumberIsNaN,
  ObjectIs,
  StringFromCharCode,
  StringPrototypeCharCodeAt,
  StringPrototypeSlice,
  StringPrototypeStartsWith,
  TypedArrayPrototypeMap,
} = primordials;

const {
	MAX_BIGINT_MAGNITUDE_BYTES,
	PREFIX_LOW_MARKER,
	STRING_ESCAPE,
	STRING_TERMINATOR,
	TAG_BIGINT,
	TAG_BOOLEAN,
	TAG_NUMBER,
	TAG_STRING,
} = require('internal/kvstore/constants');
const {
	exceedsKeyByteLimit,
	getType,
	isString,
	UNKNOWN_TYPE,
} = require('internal/kvstore/utils');
const {
  ERR_INVALID_ARG_TYPE,
  ERR_INVALID_ARG_VALUE,
  ERR_INVALID_STATE,
  ERR_KVSTORE_BIGINT_TOO_LARGE,
  ERR_OUT_OF_RANGE,
} = require('internal/errors').codes;


// context: 'key' | 'prefix' — determines which error code is thrown.
// Two separate branches (one per context) so every throw is a direct
// `throw new ERR_KVSTORE_*` that can carry a `// @core:` annotation for
// the Node-core CJS bundle target.
function validateSegments(keys, context) {
	if (ArrayPrototypeSome(keys, (key) => isString(key) && key === "")) {
		if (context === "key") {
			throw new ERR_INVALID_ARG_VALUE('key', keys, 'segments cannot be an empty string');
		}
		throw new ERR_INVALID_ARG_VALUE('selector.prefix', keys, 'segments cannot be an empty string');
	}
	if (ArrayPrototypeSome(keys, (key) => getType(key) === UNKNOWN_TYPE)) {
		if (context === "key") {
			throw new ERR_INVALID_ARG_VALUE('key', keys, 'segments must be a string, number, bigint, or boolean');
		}
		throw new ERR_INVALID_ARG_VALUE('selector.prefix', keys, 'segments must be a string, number, bigint, or boolean');
	}
	if (ArrayPrototypeSome(keys, (key) => typeof key === "number" && NumberIsNaN(key))) {
		if (context === "key") {
			throw new ERR_INVALID_ARG_VALUE('key', keys, 'NaN is not a valid key segment');
		}
		throw new ERR_INVALID_ARG_VALUE('selector.prefix', keys, 'NaN is not a valid key segment');
	}
}

function validateKeys(keys) {
	if (!ArrayIsArray(keys)) {
		throw new ERR_INVALID_ARG_TYPE('key', 'Array or string', keys);
	}
	if (keys.length < 1) {
		throw new ERR_INVALID_ARG_VALUE('key', keys, 'must have at least one segment');
	}
	validateSegments(keys, "key");
}

/**
 * Looser than `validateKeys`: an empty array is a valid prefix meaning
 * "no constraint, match every key" — `{ prefix: [] }` is the documented
 * full-scan recipe.
 */
function validatePrefixSegments(keys) {
	if (!ArrayIsArray(keys)) {
		throw new ERR_INVALID_ARG_TYPE('selector.prefix', 'Array or string', keys);
	}
	validateSegments(keys, "prefix");
}

/**
 * Copies an array input so the normalized key returned to callers (and
 * stashed in `get`/`getMany`/`delete`/`watch` results) never aliases the
 * caller's own array — mirrors the clone-on-read guarantee already made for
 * values (see `set()`'s doc comment in kv.mjs). The string-shorthand path
 * already allocates a fresh array, so only the array path needs a copy.
 */
function toOwnedArray(rawKeys) {
	if (isString(rawKeys)) return [rawKeys];
	return ArrayIsArray(rawKeys) ? ArrayPrototypeSlice(rawKeys) : rawKeys;
}

function normalizeKeys(rawKeys) {
	const keys = toOwnedArray(rawKeys);
	validateKeys(keys);
	return keys;
}

function normalizePrefixKeys(rawKeys) {
	const keys = toOwnedArray(rawKeys);
	validatePrefixSegments(keys);
	return keys;
}

function toBinaryString(buf) {
	return buf.toString("latin1");
}

function toBuffer(binaryString) {
	return Buffer.from(binaryString, "latin1");
}

// --- string segment: escape+terminate, preserves UTF-8 byte order ---------

function encodeStringSegment(value) {
	const bytes = Buffer.from(value, "utf8");
	let out = StringFromCharCode(TAG_STRING);
	for (const byte of bytes) {
		const ch = StringFromCharCode(byte);
		out +=
			ch === STRING_TERMINATOR || ch === STRING_ESCAPE
				? STRING_ESCAPE + ch
				: ch;
	}
	return out + STRING_TERMINATOR;
}

function decodeStringSegment(str, offset) {
	let raw = "";
	let i = offset;
	for (;;) {
		const ch = str[i];
		if (ch === undefined) {
			throw new ERR_INVALID_STATE('corrupt key encoding: truncated string segment');
		}
		if (ch === STRING_ESCAPE) {
			raw += str[i + 1];
			i += 2;
			continue;
		}
		if (ch === STRING_TERMINATOR) {
			i += 1;
			break;
		}
		raw += ch;
		i += 1;
	}
	return { value: toBuffer(raw).toString("utf8"), nextOffset: i };
}

// --- number segment: sign-flipped float64, order-preserving ---------------

const SIGN_MASK = 0x8000000000000000n;
const ALL_ONES_64 = 0xffffffffffffffffn;

function encodeNumberSegment(value) {
	if (NumberIsNaN(value)) {
		throw new ERR_INVALID_ARG_VALUE('key', value, 'NaN is not a valid key segment');
	}
	const normalized = ObjectIs(value, -0) ? 0 : value;
	const raw = Buffer.alloc(8);
	raw.writeDoubleBE(normalized, 0);
	const bits = raw.readBigUInt64BE(0);
	const flipped = bits & SIGN_MASK ? ~bits & ALL_ONES_64 : bits | SIGN_MASK;
	const out = Buffer.alloc(8);
	out.writeBigUInt64BE(flipped, 0);
	return StringFromCharCode(TAG_NUMBER) + toBinaryString(out);
}

function decodeNumberSegment(str, offset) {
	const buf = toBuffer(str.slice(offset, offset + 8));
	const bits = buf.readBigUInt64BE(0);
	const unflipped =
		bits & SIGN_MASK ? bits & ~SIGN_MASK & ALL_ONES_64 : ~bits & ALL_ONES_64;
	const out = Buffer.alloc(8);
	out.writeBigUInt64BE(unflipped, 0);
	return { value: out.readDoubleBE(0), nextOffset: offset + 8 };
}

// --- bigint segment: sign + order-corrected length + magnitude ------------

function bigintMagnitudeBytes(abs) {
	if (abs === 0n) return Buffer.alloc(0);
	let hex = BigIntPrototypeToString(abs, 16);
	if (hex.length % 2 !== 0) hex = `0${hex}`;
	return Buffer.from(hex, "hex");
}

function encodeBigintSegment(value) {
	const negative = value < 0n;
	const magnitude = bigintMagnitudeBytes(negative ? -value : value);
	if (magnitude.length > MAX_BIGINT_MAGNITUDE_BYTES) {
		throw new ERR_KVSTORE_BIGINT_TOO_LARGE(MAX_BIGINT_MAGNITUDE_BYTES);
	}
	// For negative values, both the length byte and every magnitude byte are
	// bit-complemented so that a larger magnitude (a more negative number)
	// sorts *before* a smaller one.
	const signByte = negative ? 0 : 1;
	const lengthByte = negative ? 0xff ^ magnitude.length : magnitude.length;
	const magBytes = negative
		? Buffer.from(TypedArrayPrototypeMap(magnitude, (b) => 0xff ^ b))
		: magnitude;
	return (
		StringFromCharCode(TAG_BIGINT, signByte, lengthByte) +
		toBinaryString(magBytes)
	);
}

function decodeBigintSegment(str, offset) {
	const signByte = StringPrototypeCharCodeAt(str, offset);
	const negative = signByte === 0;
	const rawLengthByte = StringPrototypeCharCodeAt(str, offset + 1);
	const length = negative ? 0xff ^ rawLengthByte : rawLengthByte;
	const start = offset + 2;
	let magBytes = toBuffer(StringPrototypeSlice(str, start, start + length));
	if (negative) magBytes = Buffer.from(TypedArrayPrototypeMap(magBytes, (b) => 0xff ^ b));
	const abs =
		magBytes.length === 0 ? 0n : BigInt(`0x${magBytes.toString("hex")}`);
	return { value: negative ? -abs : abs, nextOffset: start + length };
}

// --- boolean segment: single byte ------------------------------------------

function encodeBooleanSegment(value) {
	return StringFromCharCode(TAG_BOOLEAN, value ? 1 : 0);
}

function decodeBooleanSegment(str, offset) {
	return { value: StringPrototypeCharCodeAt(str, offset) === 1, nextOffset: offset + 1 };
}

// --- segment dispatch -------------------------------------------------------

function encodeSegment(segment) {
	const type = getType(segment);
	switch (type) {
		case "string":
			return encodeStringSegment(segment);
		case "number":
			return encodeNumberSegment(segment);
		case "bigint":
			return encodeBigintSegment(segment);
		case "boolean":
			return encodeBooleanSegment(segment);
		default:
			throw new ERR_INVALID_ARG_VALUE('key', segment, 'segments must be a string, number, bigint, or boolean');
	}
}

function decodeSegment(str, offset) {
	const tag = StringPrototypeCharCodeAt(str, offset);
	switch (tag) {
		case TAG_STRING:
			return decodeStringSegment(str, offset + 1);
		case TAG_NUMBER:
			return decodeNumberSegment(str, offset + 1);
		case TAG_BIGINT:
			return decodeBigintSegment(str, offset + 1);
		case TAG_BOOLEAN:
			return decodeBooleanSegment(str, offset + 1);
		default:
			throw new ERR_INVALID_STATE('corrupt key encoding: unknown segment tag');
	}
}

function serializeKeys(keys) {
	return ArrayPrototypeJoin(ArrayPrototypeMap(keys, encodeSegment), "");
}

function deserializeKeys(serialized) {
	const segments = [];
	let offset = 0;
	while (offset < serialized.length) {
		const { value, nextOffset } = decodeSegment(serialized, offset);
		segments.push(value);
		offset = nextOffset;
	}
	return segments;
}

/**
 * Normalize and serialize a raw key in one pass — the entry point for a
 * *concrete* key (get/set/delete, range bounds, watch key/keys). Requires
 * at least one segment.
 * @param {string|Array} rawKey
 * @returns {{normalized: Array, encoded: string}}
 */
function encodeKey(rawKey) {
	const normalized = normalizeKeys(rawKey);
	const encoded = serializeKeys(normalized);
	if (exceedsKeyByteLimit(encoded)) {
		throw new ERR_OUT_OF_RANGE('key', `<= ${MAX_KEY_BYTE_LENGTH} bytes`, `${encoded.length} bytes`);
	}
	return { normalized, encoded };
}

/**
 * Like `encodeKey`, but for a selector's `prefix` field: an empty array is
 * valid and means "match every key" (see `validatePrefixSegments`).
 * @param {string|Array} rawPrefix
 * @returns {{normalized: Array, encoded: string}}
 */
function encodePrefix(rawPrefix) {
	const normalized = normalizePrefixKeys(rawPrefix);
	const encoded = serializeKeys(normalized);
	if (exceedsKeyByteLimit(encoded)) {
		throw new ERR_OUT_OF_RANGE('selector.prefix', `<= ${MAX_KEY_BYTE_LENGTH} bytes`, `${encoded.length} bytes`);
	}
	return { normalized, encoded };
}

/**
 * Compute the [start, end) bounds of an encoded prefix for sargable range
 * queries under BLOB memcmp ordering. `end` is `null` when the prefix has
 * no finite successor (every byte is 0xFF) — callers must treat that as
 * "no upper bound" rather than binding a literal null-as-value.
 * @param {string} encodedPrefix
 * @returns {{start: string, end: string|null}}
 */
function prefixBounds(encodedPrefix) {
	return {
		start: encodedPrefix + PREFIX_LOW_MARKER,
		end: successor(encodedPrefix),
	};
}

function successor(str) {
	for (let i = str.length - 1; i >= 0; i--) {
		const code = StringPrototypeCharCodeAt(str, i);
		if (code < 0xff) {
			return StringPrototypeSlice(str, 0, i) + StringFromCharCode(code + 1);
		}
	}
	return null;
}

function isGreater(startKey, endKey) {
	return encodeKey(startKey).encoded > encodeKey(endKey).encoded;
}

function isInPrefix(key, encodedPrefix) {
	const encodedKey = encodeKey(key).encoded;
	return (
		StringPrototypeStartsWith(encodedKey, encodedPrefix) &&
		encodedKey.length > encodedPrefix.length
	);
}

// Presence checks below use `!== undefined`, not truthiness — `""` is a
// falsy-but-valid KeyValue (shorthand for a single empty-string segment,
// which is itself invalid and must fail with a clear "empty string segment"
// error from encodePrefix/encodeKey, not be silently treated as "absent").
function validateSelectorKeys(selector) {
	if (!selector || typeof selector !== "object") {
		throw new ERR_INVALID_ARG_TYPE('selector', 'Object', selector);
	}
	if (selector.prefix !== undefined) {
		const { encoded: encodedPrefix } = encodePrefix(selector.prefix);
		if (
			selector.start !== undefined &&
			!isInPrefix(selector.start, encodedPrefix)
		) {
			throw new ERR_INVALID_ARG_VALUE('selector.start', selector.start, 'is not in the key space defined by prefix');
		}
		if (
			selector.end !== undefined &&
			!isInPrefix(selector.end, encodedPrefix)
		) {
			throw new ERR_INVALID_ARG_VALUE('selector.end', selector.end, 'is not in the key space defined by prefix');
		}
		if (
			selector.start !== undefined &&
			selector.end !== undefined &&
			isGreater(selector.start, selector.end)
		) {
			throw new ERR_INVALID_ARG_VALUE('selector.start', selector.start, 'is greater than end key');
		}
		return;
	}
	if (selector.start === undefined || selector.end === undefined) {
		throw new ERR_INVALID_ARG_VALUE('selector', selector, 'range selector requires both start and end keys');
	}
	if (isGreater(selector.start, selector.end)) {
		throw new ERR_INVALID_ARG_VALUE('selector.start', selector.start, 'is greater than end key');
	}
}

function findBySelector(selector, db) {
	validateSelectorKeys(selector);
	if (selector.prefix === undefined) {
		return db.range(
			encodeKey(selector.start).encoded,
			encodeKey(selector.end).encoded,
		);
	}
	const { encoded: encodedPrefix } = encodePrefix(selector.prefix);
	return db.prefix(encodedPrefix, {
		start:
			selector.start != null ? encodeKey(selector.start).encoded : undefined,
		end: selector.end != null ? encodeKey(selector.end).encoded : undefined,
	});
}

module.exports = {
  deserializeKeys,
  encodeKey,
  encodePrefix,
  findBySelector,
  normalizeKeys,
  prefixBounds,
  serializeKeys,
};
