// Auto-generated by `node tools/doc/addon-verify.js`
'use strict';
const common = require('../../common');
// test.js
const createObject = require(`./build/${common.buildType}/binding`);

const obj = createObject(10);
console.log(obj.plusOne());
// Prints: 11
console.log(obj.plusOne());
// Prints: 12
console.log(obj.plusOne());
// Prints: 13

const obj2 = createObject(20);
console.log(obj2.plusOne());
// Prints: 21
console.log(obj2.plusOne());
// Prints: 22
console.log(obj2.plusOne());
// Prints: 23
