name: "\U0001F680 Feature request"
description: Suggest an idea for this project
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to make Node.js better.

        Please fill in as much of the following form as you're able.
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
