'use strict';

const {
  ObjectFreeze,
} = primordials;

const codes = ObjectFreeze({
  __proto__: null,
  INVALID_TYPE: 'INVALID_TYPE',
  MISSING_REQUIRED: 'MISSING_REQUIRED',
  STRING_TOO_SHORT: 'STRING_TOO_SHORT',
  STRING_TOO_LONG: 'STRING_TOO_LONG',
  PATTERN_MISMATCH: 'PATTERN_MISMATCH',
  ENUM_MISMATCH: 'ENUM_MISMATCH',
  NUMBER_TOO_SMALL: 'NUMBER_TOO_SMALL',
  NUMBER_TOO_LARGE: 'NUMBER_TOO_LARGE',
  NUMBER_NOT_MULTIPLE: 'NUMBER_NOT_MULTIPLE',
  NOT_INTEGER: 'NOT_INTEGER',
  ARRAY_TOO_SHORT: 'ARRAY_TOO_SHORT',
  ARRAY_TOO_LONG: 'ARRAY_TOO_LONG',
  ADDITIONAL_PROPERTY: 'ADDITIONAL_PROPERTY',
});

module.exports = {
  codes,
};
