// Auto-generated by scripts/bundle.mjs from src/kv.test.mjs — do not edit directly.
// Regenerate with: npm run bundle
'use strict';

const { skipIfKVStoreMissing } = require('../common');
skipIfKVStoreMissing();

const assert = require('node:assert/strict');
const { existsSync, mkdtempSync, rmSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { join } = require('node:path');
const { afterEach, beforeEach, describe, it } = require('node:test');
const { KVStore, openKv } = require('node:kvstore');

async function collectN(stream, n) {
	const out = [];
	for await (const event of stream) {
		out.push(event);
		if (out.length === n) break;
	}
	return out;
}

describe("KV instance", () => {
	let kv;

	beforeEach(() => {
		kv = openKv();
	});

	afterEach(() => {
		kv.close();
	});

	it("openKv() returns a KVStore instance", () => {
		assert.ok(kv instanceof KVStore);
	});

	it("should set and get a value", () => {
		const testKey = [1, "test", false, 2n];
		const testValue = { foo: "bar" };

		kv.set(testKey, testValue);

		const result = kv.get(testKey);
		assert.deepEqual(result, { key: testKey, value: testValue });
	});

	it("set() returns undefined", () => {
		assert.strictEqual(kv.set(["a"], 1), undefined);
	});

	it("get() returns a key independent from the caller's input array (regression: key-aliasing)", () => {
		const key = ["a", 1];
		kv.set(key, "v");
		const result = kv.get(key);
		key.push("mutated-after-get");
		assert.deepEqual(result.key, ["a", 1]);
		assert.notStrictEqual(result.key, key);
	});

	it("getMany() returns keys independent from the caller's input arrays (regression: key-aliasing)", () => {
		const key = ["a", 1];
		kv.set(key, "v");
		const [result] = kv.getMany([key]);
		key.push("mutated-after-getMany");
		assert.deepEqual(result.key, ["a", 1]);
		assert.notStrictEqual(result.key, key);
	});

	it("delete()'s watch event carries a key independent from the caller's input array (regression: key-aliasing)", async () => {
		const key = ["a", 1];
		kv.set(key, "v");
		const sub = kv.watch({ key });
		kv.delete(key);
		key.push("mutated-after-delete");
		const [event] = await collectN(sub, 1);
		assert.deepEqual(event, { type: "delete", key: ["a", 1] });
		sub.destroy();
	});

	it("should get multiple entry at once", () => {
		const testKeys = [
			[1, "test", false, 2n],
			[2, "test2", true, 3n],
		];
		const testValues = [{ foo: "bar" }, { foo: "baz" }];

		kv.set(testKeys[0], testValues[0]);
		kv.set(testKeys[1], testValues[1]);

		const results = kv.getMany(testKeys);
		assert.deepEqual(results, [
			{ key: testKeys[0], value: testValues[0] },
			{ key: testKeys[1], value: testValues[1] },
		]);
	});

	it("should round-trip rich value types (Date, BigInt, Map, Set, RegExp, undefined)", () => {
		const value = {
			when: new Date("2024-01-15T10:30:00Z"),
			count: 9007199254740993n,
			tags: new Set(["a", "b"]),
			lookup: new Map([["x", 1]]),
			pattern: /foo/gi,
			missing: undefined,
			nested: { typed: new Uint8Array([1, 2, 3]) },
		};
		kv.set(["rich"], value);
		const { value: round } = kv.get(["rich"]);
		assert.deepStrictEqual(round, value);
	});

	it("should round-trip circular references", () => {
		const a = { name: "a" };
		a.self = a;
		kv.set(["cyc"], a);
		const { value } = kv.get(["cyc"]);
		assert.strictEqual(value.self, value);
		assert.strictEqual(value.name, "a");
	});

	it("getMany should reject non-array input", () => {
		for (const bad of ["not-an-array", null, undefined, 123]) {
			assert.throws(() => kv.getMany(bad), {
				name: "TypeError",
				code: "ERR_INVALID_ARG_TYPE",
			});
		}
	});

	it("getMany should reject an empty array", () => {
		assert.throws(() => kv.getMany([]), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("getMany should preserve input order", () => {
		kv.set(["a"], 1);
		kv.set(["b"], 2);
		kv.set(["c"], 3);
		const result = kv.getMany([["c"], ["a"], ["b"]]);
		assert.deepEqual(result, [
			{ key: ["c"], value: 3 },
			{ key: ["a"], value: 1 },
			{ key: ["b"], value: 2 },
		]);
	});

	it("getMany should yield duplicates when the input contains them", () => {
		kv.set(["a"], 1);
		const result = kv.getMany([["a"], ["a"]]);
		assert.deepEqual(result, [
			{ key: ["a"], value: 1 },
			{ key: ["a"], value: 1 },
		]);
	});

	it("getMany should return null for missing keys", () => {
		kv.set(["existing"], "exists");
		const result = kv.getMany([["existing"], ["non-existing"]]);
		assert.deepEqual(result, [
			{ key: ["existing"], value: "exists" },
			{ key: ["non-existing"], value: null },
		]);
	});

	it("getMany should correctly match keys of mixed segment types (regression: BLOB vs json_each)", () => {
		kv.set(["a"], "string-key");
		kv.set([2], "number-key");
		kv.set([3n], "bigint-key");
		kv.set([true], "bool-key");
		const result = kv.getMany([["a"], [2], [3n], [true], ["missing"]]);
		assert.deepEqual(result, [
			{ key: ["a"], value: "string-key" },
			{ key: [2], value: "number-key" },
			{ key: [3n], value: "bigint-key" },
			{ key: [true], value: "bool-key" },
			{ key: ["missing"], value: null },
		]);
	});

	it("getMany works across IN(...) chunk boundaries (regression: H3 chunking)", () => {
		const n = 1200; // > MAX_IN_CLAUSE_VARIABLES (500), spans 3 chunks
		for (let i = 0; i < n; i++) kv.set([i], `v${i}`);
		const keys = Array.from({ length: n }, (_, i) => [i]);
		const result = kv.getMany(keys);
		assert.equal(result.length, n);
		for (let i = 0; i < n; i++) {
			assert.deepEqual(result[i], { key: [i], value: `v${i}` });
		}
	});

	it("getMany does not throw past the historical SQLite variable limit (regression: H3)", () => {
		const n = 40000; // > the old, unchunked SQLITE_MAX_VARIABLE_NUMBER ceiling
		for (let i = 0; i < n; i++) kv.set([i], i);
		const keys = Array.from({ length: n }, (_, i) => [i]);
		const result = kv.getMany(keys);
		assert.equal(result.length, n);
		assert.deepEqual(result[0], { key: [0], value: 0 });
		assert.deepEqual(result[n - 1], { key: [n - 1], value: n - 1 });
	});

	it("should return false when deleting a missing key", () => {
		assert.strictEqual(kv.delete(["never-set"]), false);
	});

	it("should delete a entry by the provided key", () => {
		const testKey = [1, "test", false, 2n];
		const testValue = { foo: "bar" };

		kv.set(testKey, testValue);

		assert.deepEqual(kv.get(testKey), { key: testKey, value: testValue });

		kv.delete(testKey);

		assert.deepEqual(kv.get(testKey), { key: testKey, value: null });
	});

	function testKeyIterator(iterator, nValues, criteria) {
		let counter = 0;
		for (const { key } of iterator) {
			assert.ok(criteria(key));
			counter++;
		}
		assert.strictEqual(counter, nValues);
	}

	it("should retrieve keys by range query - numeric values in true numeric order (regression: N1)", () => {
		const values = [1, 2, 3, 9, 10, 11, 20, 100];
		for (const n of values) kv.set([n], `value${n}`);

		const got = [...kv.keys({ start: [1], end: [100] })].map((e) => e.key[0]);
		assert.deepEqual(got, values);
	});

	it("should retrieve keys by range query - negative and fractional numbers in true numeric order", () => {
		const values = [-300, -5, -3, -1.5, 0, 1.5, 5];
		for (const n of values) kv.set([n], `value${n}`);

		const got = [...kv.keys({ start: [-300], end: [5] })].map((e) => e.key[0]);
		assert.deepEqual(got, values);
	});

	it("should retrieve keys by range query - bigint values in true numeric order", () => {
		const values = [-256n, -5n, -3n, 0n, 5n, 256n];
		for (const n of values) kv.set([n], `value${n}`);

		const got = [...kv.keys({ start: [-256n], end: [256n] })].map(
			(e) => e.key[0],
		);
		assert.deepEqual(got, values);
	});

	it("should retrieve keys by range query - string values", () => {
		const entries = [
			{ key: ["a"], value: "value1" },
			{ key: ["b"], value: "value2" },
			{ key: ["c"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ start: ["a"], end: ["c"] });
		testKeyIterator(iterator, 3, (key) => ["a", "b", "c"].includes(key[0]));
	});

	it("should retrieve keys by range query avoiding partial matching - nested values", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ start: ["users", "a"], end: ["users", "b"] });
		testKeyIterator(iterator, 1, (key) => key[1] === "alice");
	});

	it("should retrieve keys by range query - nested values", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ start: ["users", "a"], end: ["users", "c"] });
		testKeyIterator(iterator, 2, (key) => ["alice", "bob"].includes(key[1]));
	});

	it("should throw if start key is greater than end key", () => {
		assert.throws(
			() => kv.keys({ start: ["users", "b"], end: ["users", "a"] }),
			{ name: "TypeError", code: "ERR_INVALID_ARG_VALUE" },
		);
	});

	it("should throw if range query is missing either start or end", () => {
		assert.throws(() => kv.keys({ start: ["users", "b"] }), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
		assert.throws(() => kv.keys({ end: ["users", "b"] }), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("should throw for a selector that isn't an object (regression: coverage gap)", () => {
		for (const bad of [null, undefined, 42, "foo", true]) {
			assert.throws(
				() => kv.keys(bad),
				(err) => {
					assert.ok(err instanceof TypeError);
					assert.equal(err.code, "ERR_INVALID_ARG_TYPE");
					return true;
				},
			);
		}
	});

	it("should throw if start key is greater than end key within a prefix selector (regression: coverage gap)", () => {
		assert.throws(
			() =>
				kv.keys({
					prefix: ["users"],
					start: ["users", "c"],
					end: ["users", "b"],
				}),
			(err) => {
				assert.ok(err instanceof TypeError);
				assert.equal(err.code, "ERR_INVALID_ARG_VALUE");
				return true;
			},
		);
	});

	it("{ prefix: '' } reports the empty-string-segment error, not a range-selector error (regression: falsy-prefix)", () => {
		assert.throws(
			() => kv.keys({ prefix: "" }),
			(err) => {
				assert.ok(err instanceof TypeError);
				assert.equal(err.code, "ERR_INVALID_ARG_VALUE");
				assert.match(err.message, /empty string/);
				return true;
			},
		);
	});

	it("should retrieve keys by prefix query", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
			{ key: ["admins", "carol"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ prefix: ["users"] });
		testKeyIterator(iterator, 2, (key) => key[0] === "users");
	});

	it("should retrieve keys by prefix query without partial matching", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
			{ key: ["admins", "carol"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ prefix: ["users", "a"] });
		testKeyIterator(iterator, 0, () => true);
	});

	it("prefix query does not match the prefix key itself", () => {
		kv.set(["user"], "exact");
		kv.set(["user", 1], "child");
		const got = [...kv.keys({ prefix: ["user"] })].map((e) => e.key);
		assert.deepEqual(got, [["user", 1]]);
	});

	it("should retrieve keys by prefix query with start key provided", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
			{ key: ["admins", "carol"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ prefix: ["users"], start: ["users", "b"] });
		testKeyIterator(
			iterator,
			1,
			(key) => key[0] === "users" && key[1] === "bob",
		);
	});

	it("should throw if start key is not within prefix", () => {
		assert.throws(
			() => kv.keys({ prefix: ["users", "a"], start: ["users", "a"] }),
			{ name: "TypeError", code: "ERR_INVALID_ARG_VALUE" },
		);
		assert.throws(
			() => kv.keys({ prefix: ["users", "a"], start: ["users", "b"] }),
			{ name: "TypeError", code: "ERR_INVALID_ARG_VALUE" },
		);
		// an empty array isn't a valid concrete key at all, regardless of prefix
		assert.throws(() => kv.keys({ prefix: ["users", "a"], start: [] }), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("should retrieve keys by prefix query with end key provided", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
			{ key: ["admins", "carol"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({ prefix: ["users"], end: ["users", "b"] });
		testKeyIterator(
			iterator,
			1,
			(key) => key[0] === "users" && key[1] === "alice",
		);
	});

	it("should retrieve keys by prefix query with both start and end", () => {
		const entries = [
			{ key: ["users", "alice"], value: "value1" },
			{ key: ["users", "bob"], value: "value2" },
			{ key: ["users", "carol"], value: "value3" },
		];
		for (const { key, value } of entries) {
			kv.set(key, value);
		}

		const iterator = kv.keys({
			prefix: ["users"],
			start: ["users", "b"],
			end: ["users", "c"],
		});
		testKeyIterator(iterator, 1, (key) => key[1] === "bob");
	});

	it("should throw if end key is not within prefix", () => {
		assert.throws(
			() => kv.keys({ prefix: ["users", "a"], end: ["users", "a"] }),
			{ name: "TypeError", code: "ERR_INVALID_ARG_VALUE" },
		);
		assert.throws(
			() => kv.keys({ prefix: ["users", "a"], end: ["users", "b"] }),
			{ name: "TypeError", code: "ERR_INVALID_ARG_VALUE" },
		);
		// an empty array isn't a valid concrete key at all, regardless of prefix
		assert.throws(() => kv.keys({ prefix: ["users", "a"], end: [] }), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("{ prefix: [] } scans every key in the store (regression: N2)", () => {
		kv.set(["users", "alice"], 1);
		kv.set(["admins", "carol"], 2);
		kv.set([42], 3);
		const got = [...kv.keys({ prefix: [] })].map((e) => e.key);
		assert.equal(got.length, 3);
		assert.ok(got.some((k) => k[0] === "users"));
		assert.ok(got.some((k) => k[0] === "admins"));
		assert.ok(got.some((k) => k[0] === 42));
	});

	it("two interleaved keys() iterators each yield their own full, correct result set (regression: N3)", () => {
		for (let i = 0; i < 10; i++) kv.set([i], i);

		const it1 = kv.keys({ start: [0], end: [4] })[Symbol.iterator]();
		const it2 = kv.keys({ start: [5], end: [9] })[Symbol.iterator]();
		const r1 = [];
		const r2 = [];
		let a = it1.next();
		let b = it2.next();
		while (!a.done || !b.done) {
			if (!a.done) {
				r1.push(a.value.key[0]);
				a = it1.next();
			}
			if (!b.done) {
				r2.push(b.value.key[0]);
				b = it2.next();
			}
		}
		assert.deepEqual(r1, [0, 1, 2, 3, 4]);
		assert.deepEqual(r2, [5, 6, 7, 8, 9]);
	});

	it("keys() iterable can be safely re-iterated (regression: H4)", () => {
		kv.set(["a"], 1);
		kv.set(["b"], 2);
		const iterable = kv.keys({ prefix: [] });
		const first = [...iterable].map((e) => e.key);
		const second = [...iterable].map((e) => e.key);
		assert.deepEqual(first, [["a"], ["b"]]);
		assert.deepEqual(second, [["a"], ["b"]]);
	});

	it("NaN is not a valid key segment", () => {
		assert.throws(() => kv.set([NaN], "x"), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("a bigint exceeding the 255-byte magnitude limit throws ERR_KVSTORE_BIGINT_TOO_LARGE", () => {
		const huge = 2n ** 2100n;
		assert.throws(
			() => kv.set([huge], "x"),
			(err) => {
				assert.ok(err instanceof RangeError);
				assert.equal(err.code, "ERR_KVSTORE_BIGINT_TOO_LARGE");
				return true;
			},
		);
	});

	it("whitespace-only string segments are valid keys", () => {
		kv.set([" "], "space");
		assert.deepEqual(kv.get([" "]), { key: [" "], value: "space" });
	});

	it("empty string segments are still rejected", () => {
		assert.throws(() => kv.set([""], "x"), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("should throw on operations after close()", () => {
		kv.close();
		const closedMatcher = { name: "Error", code: "ERR_KVSTORE_CLOSED" };
		assert.throws(() => kv.get(["x"]), closedMatcher);
		assert.throws(() => kv.set(["x"], "v"), closedMatcher);
		assert.throws(() => kv.delete(["x"]), closedMatcher);
		assert.throws(() => kv.clear(), closedMatcher);
		// re-open for the afterEach close
		kv = openKv();
	});

	it("close() should be idempotent", () => {
		kv.close();
		assert.doesNotThrow(() => kv.close());
		kv = openKv();
	});
});

describe("KV constructor", () => {
	it("defaults to an in-memory store with no disk side effect", () => {
		const a = openKv();
		a.set(["x"], "in-memory");
		assert.deepEqual(a.get(["x"]), { key: ["x"], value: "in-memory" });
		a.close();
	});

	it("two default (in-memory) instances should not share state", () => {
		const a = openKv();
		const b = openKv();
		a.set(["x"], "from-a");
		assert.deepEqual(b.get(["x"]), { key: ["x"], value: null });
		assert.deepEqual(a.get(["x"]), { key: ["x"], value: "from-a" });
		a.close();
		b.close();
	});

	it("closing one instance should not affect another", () => {
		const a = openKv();
		const b = openKv();
		a.close();
		assert.doesNotThrow(() => b.set(["y"], "still-works"));
		b.close();
	});
});

describe("watch / publish", () => {
	let kv;

	beforeEach(() => {
		kv = openKv();
	});

	afterEach(() => {
		kv.close();
	});

	it("exact-key watcher sees set and delete on its key only", async () => {
		const sub = kv.watch({ key: ["a"] });
		kv.set(["a"], 1);
		kv.set(["b"], 2); // ignored
		kv.delete(["a"]);
		const events = await collectN(sub, 2);
		assert.deepEqual(events, [
			{ type: "set", key: ["a"], value: 1 },
			{ type: "delete", key: ["a"] },
		]);
		sub.destroy();
	});

	it("watch() delivers an isolated clone, not the caller's live object (regression: H2)", async () => {
		const sub = kv.watch({ key: ["a"] });
		const obj = { foo: "bar" };
		kv.set(["a"], obj);
		obj.foo = "mutated-after-set";

		const [event] = await collectN(sub, 1);
		assert.deepEqual(event, {
			type: "set",
			key: ["a"],
			value: { foo: "bar" },
		});
		assert.notStrictEqual(event.value, obj);

		const stored = kv.get(["a"]);
		assert.deepEqual(stored.value, { foo: "bar" });
		sub.destroy();
	});

	it("watch() delivers a key independent from the caller's live array (regression: key-aliasing)", async () => {
		const sub = kv.watch({ prefix: [] });
		const key = ["a", 1];
		kv.set(key, "v");
		key.push("mutated-after-set");

		const [event] = await collectN(sub, 1);
		assert.deepEqual(event, { type: "set", key: ["a", 1], value: "v" });
		assert.notStrictEqual(event.key, key);
		sub.destroy();
	});

	it("prefix watcher matches nested keys, ignores siblings", async () => {
		const sub = kv.watch({ prefix: ["user"] });
		kv.set(["user", 1], "alice");
		kv.set(["admin", 1], "carol"); // ignored
		kv.set(["user", 2, "profile"], { v: 1 });
		kv.delete(["user", 1]);
		const events = await collectN(sub, 3);
		assert.deepEqual(events, [
			{ type: "set", key: ["user", 1], value: "alice" },
			{ type: "set", key: ["user", 2, "profile"], value: { v: 1 } },
			{ type: "delete", key: ["user", 1] },
		]);
		sub.destroy();
	});

	it("prefix watcher does NOT match the prefix key itself", async () => {
		const sub = kv.watch({ prefix: ["user"] });
		kv.set(["user"], "exact"); // ignored — at prefix, not under it
		kv.set(["user", 1], "child");
		const [event] = await collectN(sub, 1);
		assert.deepEqual(event, { type: "set", key: ["user", 1], value: "child" });
		sub.destroy();
	});

	it("keys watcher fires for any of the listed keys, ignores others", async () => {
		const sub = kv.watch({ keys: [["a"], ["b"]] });
		kv.set(["a"], 1);
		kv.set(["c"], 99); // ignored
		kv.set(["b"], 2);
		kv.delete(["a"]);
		const events = await collectN(sub, 3);
		assert.deepEqual(events, [
			{ type: "set", key: ["a"], value: 1 },
			{ type: "set", key: ["b"], value: 2 },
			{ type: "delete", key: ["a"] },
		]);
		sub.destroy();
	});

	it("keys watcher receives clear like other key watchers", async () => {
		const sub = kv.watch({ keys: [["a"], ["b"]] });
		kv.set(["a"], 1);
		kv.clear();
		const events = await collectN(sub, 2);
		assert.deepEqual(events, [
			{ type: "set", key: ["a"], value: 1 },
			{ type: "clear" },
		]);
		sub.destroy();
	});

	it("keys watcher rejects empty array", () => {
		assert.throws(() => kv.watch({ keys: [] }), {
			name: "TypeError",
			code: "ERR_INVALID_ARG_VALUE",
		});
	});

	it("events filter excludes unwanted types", async () => {
		const sub = kv.watch({ prefix: ["x"], events: ["set"] });
		kv.set(["x", 1], "v");
		kv.delete(["x", 1]); // ignored
		kv.set(["x", 2], "w");
		const events = await collectN(sub, 2);
		assert.deepEqual(events, [
			{ type: "set", key: ["x", 1], value: "v" },
			{ type: "set", key: ["x", 2], value: "w" },
		]);
		sub.destroy();
	});

	it("clear fires on every key/prefix watcher", async () => {
		const a = kv.watch({ key: ["a"] });
		const b = kv.watch({ prefix: ["b"] });
		kv.set(["a"], 1);
		kv.set(["b", 1], 2);
		kv.clear();
		const aEvents = await collectN(a, 2);
		const bEvents = await collectN(b, 2);
		assert.deepEqual(aEvents[1], { type: "clear" });
		assert.deepEqual(bEvents[1], { type: "clear" });
		a.destroy();
		b.destroy();
	});

	it("topic watcher receives publish payloads as-is", async () => {
		const sub = kv.watch({ topic: "login" });
		kv.publish("login", { user: "alice" });
		kv.publish("login", { user: "bob" });
		const events = await collectN(sub, 2);
		assert.deepEqual(events, [{ user: "alice" }, { user: "bob" }]);
		sub.destroy();
	});

	it("topics and key channels do not cross", async () => {
		const keySub = kv.watch({ key: ["x"] });
		const topicSub = kv.watch({ topic: "x" });

		let topicFired = false;
		topicSub.on("data", () => {
			topicFired = true;
		});

		kv.set(["x"], 1);
		await new Promise((r) => setImmediate(r));
		assert.strictEqual(topicFired, false);

		const [event] = await collectN(keySub, 1);
		assert.deepEqual(event, { type: "set", key: ["x"], value: 1 });
		keySub.destroy();
		topicSub.destroy();
	});

	it("close() ends outstanding subscriptions", async () => {
		const sub = kv.watch({ prefix: ["a"] });
		kv.close();
		const events = [];
		for await (const e of sub) events.push(e);
		assert.deepEqual(events, []);
		// re-open for the afterEach close
		kv = openKv();
	});

	it("watch throws after close", () => {
		kv.close();
		assert.throws(() => kv.watch({ key: ["a"] }), {
			name: "Error",
			code: "ERR_KVSTORE_CLOSED",
		});
		kv = openKv();
	});

	it("publish throws after close", () => {
		kv.close();
		assert.throws(() => kv.publish("t", 1), {
			name: "Error",
			code: "ERR_KVSTORE_CLOSED",
		});
		kv = openKv();
	});

	it("rejects malformed selectors", () => {
		const bad = [
			undefined,
			null,
			"foo",
			{},
			{ key: "a", topic: "b" },
			{ key: "a", keys: [["b"]] },
			{ keys: "not-an-array" },
			{ keys: [] },
			{ topic: "" },
			{ topic: 123 },
			{ key: "a", events: [] },
			{ key: "a", events: ["bogus"] },
		];
		for (const sel of bad) {
			assert.throws(() => kv.watch(sel), {
				name: "TypeError",
				code: "ERR_INVALID_ARG_VALUE",
			});
		}
	});


	it("rejects malformed publish topics", () => {
		for (const topic of [undefined, null, "", 42, {}]) {
			assert.throws(() => kv.publish(topic, 1), {
				name: "TypeError",
				code: "ERR_INVALID_ARG_VALUE",
			});
		}
	});


	it("rejects highWaterMark < 1", () => {
		const matcher = { name: "TypeError", code: "ERR_OUT_OF_RANGE, name: RangeError" };
		assert.throws(
			() => kv.watch({ key: ["a"] }, { highWaterMark: 0 }),
			matcher,
		);
		assert.throws(
			() => kv.watch({ key: ["a"] }, { highWaterMark: -1 }),
			matcher,
		);
	});

	it("emits a lag event when watcher falls behind", async () => {
		const sub = kv.watch({ prefix: ["x"] }, { highWaterMark: 4 });

		// Collect everything via a single 'data' listener.
		const received = [];
		sub.on("data", (event) => received.push(event));

		// Burst: first 4 buffered (then immediately drained because the listener
		// puts the stream in flowing mode), the remaining 46 also push without
		// dropping because each push drains synchronously.
		// To force drops, we need to pause the stream before the burst.
		sub.pause();
		for (let i = 0; i < 50; i++) kv.set(["x", i], i);

		// Resume to drain the 4 buffered events.
		sub.resume();
		await new Promise((r) => setImmediate(r));
		assert.strictEqual(received.length, 4);

		// Buffer is empty; emit one more — it should be preceded by a lag event.
		kv.set(["x", 999], 999);
		await new Promise((r) => setImmediate(r));

		assert.deepEqual(received[4], { type: "lag", dropped: 46 });
		assert.deepEqual(received[5], {
			type: "set",
			key: ["x", 999],
			value: 999,
		});

		sub.destroy();
	});

	it("does not deliver events emitted after destroy()", () => {
		const sub = kv.watch({ key: ["a"] });
		const received = [];
		sub.on("data", (e) => received.push(e));
		sub.destroy();
		kv.set(["a"], "after-destroy");
		assert.deepEqual(received, []);
	});

	it("more than 10 concurrent watchers does not trigger MaxListenersExceededWarning (regression: max-listeners)", async () => {
		const warnings = [];
		const onWarning = (w) => warnings.push(w);
		process.on("warning", onWarning);
		try {
			const subs = Array.from({ length: 20 }, (_, i) =>
				kv.watch({ key: [`k${i}`] }),
			);
			kv.set(["k0"], 1);
			await new Promise((r) => setImmediate(r));
			for (const sub of subs) sub.destroy();
			// give any (unwanted) async warning a chance to surface
			await new Promise((r) => setImmediate(r));
		} finally {
			process.off("warning", onWarning);
		}
		assert.deepEqual(warnings, []);
	});
});

describe("file-backed store", () => {
	let dir;

	beforeEach(() => {
		dir = mkdtempSync(join(tmpdir(), "nonosqlite-test-"));
	});

	afterEach(() => {
		rmSync(dir, { recursive: true, force: true });
	});

	it("persists across close/reopen with correct ordering", () => {
		const path = join(dir, "store.sqlite");
		const a = openKv({ path });
		for (const n of [10, 1, 100, 2]) a.set([n], `v${n}`);
		a.close();

		const b = openKv({ path });
		const got = [...b.keys({ prefix: [] })].map((e) => e.key[0]);
		assert.deepEqual(got, [1, 2, 10, 100]);
		b.close();
	});

	it("creates WAL sidecar files while open, cleaned up on close", () => {
		const path = join(dir, "wal.sqlite");
		const kv = openKv({ path });
		kv.set(["x"], 1);
		assert.ok(existsSync(`${path}-wal`));
		kv.close();
		assert.ok(!existsSync(`${path}-wal`));
	});

	it("watch() does not observe writes made through a different KVStore instance on the same file (regression: cross-instance scope)", async () => {
		const path = join(dir, "shared.sqlite");
		const writer = openKv({ path });
		const reader = openKv({ path });

		const sub = reader.watch({ prefix: [] });
		const seen = [];
		sub.on("data", (event) => seen.push(event));

		writer.set(["from-writer"], 1);
		writer.delete(["from-writer"]);
		writer.clear();
		// Give any (wrongly) cross-instance event a chance to arrive before
		// asserting its absence.
		await new Promise((resolve) => setImmediate(resolve));

		assert.deepEqual(seen, []);

		sub.destroy();
		writer.close();
		reader.close();
	});
});
