#!/usr/bin/env node
// Generates src/node_config_schema.h from doc/node-config-schema.json.
// Run after editing the JSON. CI runs `--check` to fail on drift.
//
// Usage:
//   node tools/gen_node_config_schema.mjs          # write the header
//   node tools/gen_node_config_schema.mjs --check  # exit 1 if out of sync

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_PATH = join(ROOT, 'doc/node-config-schema.json');
const HEADER_PATH = join(ROOT, 'src/node_config_schema.h');

// `additionalProperties: false` is kept in the doc but stripped from the
// runtime copy so older Node versions don't reject configs that mention
// fields added in later releases.
function stripAdditionalProperties(node) {
  if (Array.isArray(node)) return node.map(stripAdditionalProperties);
  if (node === null || typeof node !== 'object') return node;
  const out = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === 'additionalProperties' && value === false) continue;
    out[key] = stripAdditionalProperties(value);
  }
  return out;
}

function buildHeader(schemaJson) {
  return `#ifndef SRC_NODE_CONFIG_SCHEMA_H_
#define SRC_NODE_CONFIG_SCHEMA_H_

// AUTO-GENERATED by tools/gen_node_config_schema.mjs from
// doc/node-config-schema.json. Do not edit by hand.

static constexpr const char kNodeConfigSchema[] = R"NODECONFIG(
${schemaJson}
)NODECONFIG";

#endif  // SRC_NODE_CONFIG_SCHEMA_H_
`;
}

let source;
try {
  source = JSON.parse(readFileSync(SOURCE_PATH, 'utf8'));
} catch (err) {
  console.error(
    `Failed to read or parse ${relative(ROOT, SOURCE_PATH)}: ${err.message}`,
  );
  process.exit(1);
}
const stripped = stripAdditionalProperties(source);
const expected = buildHeader(JSON.stringify(stripped, null, 2));

if (process.argv.includes('--check')) {
  const actual = readFileSync(HEADER_PATH, 'utf8');
  if (actual !== expected) {
    console.error(
      `${relative(ROOT, HEADER_PATH)} is out of date with respect to ` +
      `${relative(ROOT, SOURCE_PATH)}.\n` +
      `Run \`node tools/gen_node_config_schema.mjs\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`${relative(ROOT, HEADER_PATH)} is up to date.`);
} else {
  writeFileSync(HEADER_PATH, expected);
  console.log(`Wrote ${relative(ROOT, HEADER_PATH)}`);
}
