#!/bin/sh

git log --reverse --format='%aN <%aE>' | awk '

BEGIN {
  print "# Authors ordered by first contribution.\n";
}

{
  if ($NF in all == 0) {
    all[$NF] = 1;
    ordered[length(all)] = $0;
  }
}

END {
  for (i in ordered) {
    print ordered[i];
  }

  print "\n# Generated by tools/update-authors.sh";
}

' > AUTHORS 
