// Auto-generated by `node tools/doc/addon-verify.js`
'use strict';
const common = require('../../common');
// test.js
const binding = require(`./build/${common.buildType}/binding`);

const obj1 = binding('hello');
const obj2 = binding('world');
console.log(obj1.msg, obj2.msg);
// Prints: 'hello world'
