name: Coverage Windows

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - '**.nix'
      - eslint.config.mjs
      - '**/eslint.config_partial.mjs'
      - android-configure
      - android-configure.py
      - android-patches/**
      - benchmarks/**
      - doc/**
      - pyproject.yml
      - tsconfig.json
      - test/internet/**
      - tools/actions/**
      - tools/bootstrap/**
      - tools/dep_updaters/**
      - tools/doc/**
      - tools/eslint-rules/**
      - tools/eslint/**
      - tools/lint-md/**
      - typings/**
      - .**
      - '!.github/workflows/coverage-windows.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.nix'
      - eslint.config.mjs
      - '**/eslint.config_partial.mjs'
      - android-configure
      - android-configure.py
      - android-patches/**
      - benchmarks/**
      - doc/**
      - pyproject.yml
      - tsconfig.json
      - test/internet/**
      - tools/actions/**
      - tools/bootstrap/**
      - tools/dep_updaters/**
      - tools/doc/**
      - tools/eslint-rules/**
      - tools/eslint/**
      - tools/lint-md/**
      - typings/**
      - .**
      - '!.github/workflows/coverage-windows.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.14'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  coverage-windows:
    if: github.event.pull_request.draft == false
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Build
        run: ./vcbuild.bat clang-cl
      # TODO(bcoe): investigate tests that fail with coverage enabled
      # on Windows.
      - name: Test
        run: ./vcbuild.bat noprojgen nobuild test-ci-js; node -e 'process.exit(0)'
        env:
          NODE_V8_COVERAGE: ./coverage/tmp
      - name: Report
        run: npx c8 report
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Clean tmp
        run: npx rimraf ./coverage/tmp
      - name: Upload
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          directory: ./coverage
