name: License update
on:
  schedule:
    # 00:00:00 every Monday
    # https://crontab.guru/#0_0_*_*_1
    - cron: 0 0 * * 1
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_license:
    permissions:
      contents: write  # for gr2m/create-or-update-pull-request-action to push local changes
      pull-requests: write  # for gr2m/create-or-update-pull-request-action to create a PR
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - run: ./tools/license-builder.sh  # Run the license builder tool
      - uses: gr2m/create-or-update-pull-request-action@86ec1766034c8173518f61d2075cc2a173fb8c97  # v1.9.4
        # Creates a PR or update the Action's existing PR, or
        # no-op if the base branch is already up-to-date.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          branch: actions/license-builder
          title: 'doc: run license-builder'
          body: >
            License is likely out of date. This is an automatically generated PR by
            the `license-builder.yml` GitHub Action, which runs `license-builder.sh`
            and submits a new PR or updates an existing PR.
          commit-message: 'doc: run license-builder'
          labels: meta
