name: Ping Code Owners

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  ping-owners:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Use Node.js lts/*
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: lts/*

      - name: Install codeowners-utils
        run: npm install --no-save codeowners-utils@1.0.2

      - name: Ping code owners
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: node tools/actions/ping-owners.mjs
