name: Post-Release actions

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to generate a blog post for.
        type: string
        required: true
  release:
    types: [released]

permissions:
  contents: read

jobs:
  post-release-actions:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Trigger update-links workflow on nodejs/release-cloudflare-worker
          gh workflow run update-links.yml --repo nodejs/release-cloudflare-worker
          # Trigger create-release-post workflow on nodejs/nodejs.org
          gh workflow run create-release-post.yml --repo nodejs/nodejs.org -f version=$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
          VERSION: ${{ inputs.version || github.event.releease.tag_name }}
